language: Swift
osx_image: xcode14.2
branches:
only:
-chapter8

before_install:
-gem install fastlane --no-ri --no-rdoc --no-document
install: true
script:
-fastlane scan --scheme TAU --device "iPhone 14 Pro"
